#!/usr/bin/env node
// dtcg-to-css.mjs — emit shadcn-compatible CSS custom properties from the
// DTCG token file, so web code and Penpot designs share ONE token source.
//
// Reads  ../tokens/hologram-tokens.json  (generated by shadcn-to-dtcg.mjs)
// Writes ../css/hologram-theme.css       (:root = light, .dark = dark)
//
// --check: round-trip parity gate — every emitted color var must equal the
// direct oklch→hex conversion of the original shadcn registry value.
//
// Usage: node dtcg-to-css.mjs [--check]

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { oklchToHex } from "./shadcn-to-dtcg.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, "..", "tokens", "hologram-tokens.json"), "utf8"));
const outPath = join(here, "..", "css", "hologram-theme.css");

// Resolve {core.x.y} references against the core set.
function resolveRef(value) {
  const m = /^\{(.+)\}$/.exec(value);
  if (!m) return value;
  let node = tokens;
  for (const part of m[1].split(".")) node = node?.[part];
  if (node?.$value === undefined) throw new Error(`unresolvable ref: ${value}`);
  return resolveRef(node.$value);
}

function cssVarsOf(setName) {
  const out = {};
  for (const [name, node] of Object.entries(tokens[setName].color))
    out[name] = resolveRef(node.$value);
  return out;
}

function block(selector, vars, extra = {}) {
  const lines = Object.entries({ ...vars, ...extra })
    .map(([k, v]) => `  --${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${lines}\n}`;
}

const radiusLg = tokens.global.radius.lg.$value;
const radiusRem = `${parseFloat(radiusLg) / 16}rem`;

const css = `/* GENERATED by brand/scripts/dtcg-to-css.mjs — do not edit by hand.
 * Source of truth: brand/tokens/hologram-tokens.json
 * Derived from shadcn/ui (MIT, https://ui.shadcn.com) neutral base. */

${block(":root", cssVarsOf("light"), {
  radius: radiusRem,
  "font-sans": tokens.global.font.family.sans.$value,
  "font-mono": tokens.global.font.family.mono.$value,
})}

${block(".dark", cssVarsOf("dark"))}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css);
console.log(`wrote ${outPath}`);

if (process.argv.includes("--check")) {
  const source = JSON.parse(
    readFileSync(join(here, "..", "tokens", "source", "shadcn-neutral.json"), "utf8"));
  const failures = [];
  let total = 0;
  for (const mode of ["light", "dark"]) {
    const emitted = cssVarsOf(mode);
    for (const [name, oklch] of Object.entries(source.cssVarsV4[mode])) {
      if (name === "radius") continue;
      total++;
      if (emitted[name] !== oklchToHex(oklch))
        failures.push(`${mode}/${name}: emitted ${emitted[name]}, registry says ${oklchToHex(oklch)}`);
    }
  }
  if (failures.length) {
    console.error("ROUND-TRIP PARITY FAILED:\n" + failures.join("\n"));
    process.exit(1);
  }
  console.log(`check: ${total}/${total} color vars round-trip exactly (light+dark vs shadcn registry)`);
}
